PROYECTO/cliente/urls.py
from django.urls import path
from cliente import views
app_name = "cliente"

urlpatterns = [
    path("",views.home,name="Home"),
    path("cliente_create",views.cliente_create,name="cliente_create"),
    path("cliente_update/<int:pk>",views.cliente_update.as_view(),name="cliente_update"), 
    path("cliente_delete/<int:pk>",views.cliente_delete,name="cliente_delete"),
    path("cliente_detail/<int:pk>",views.cliente_detail,name="cliente_detail"), 
]

PROYECTO/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from core import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("cliente/",include("cliente.urls")),
    path('productos/',include('producto.urls')),
    path('accounts/profile/', views.home, name='perfil'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PROYECTO/core/urls.py
from django.urls import path     
from django.contrib.auth.views import LogoutView     
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "core"



urlpatterns = [
    path("",views.home,name="Home"),
    path("login/",views.CustomLoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(template_name="core/logout.html"),name="logout"),
    path("register/",views.register,name="register"),
    path("error/",views.Error_view.as_view(),name="Error_view"),
    path("about/",views.about,name="about")
    
]


urlpatterns += staticfiles_urlpatterns()

PROYECTO/producto/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "producto"

urlpatterns = [
    path("",login_required(views.home),name="Home"),
    path("productocategoria/create/",views.productocategoria_create.as_view(),name="productocategoria_create"),

    path("productos_buscador_categoria/",login_required(views.home_1),name="buscador_productos"),
    
    path("productos_caracteristicas/<int:fk>",views.productos_caracteristicas,name="productos_caracteristicas"),
    
    path("producto_update/<int:pk>",views.producto_update.as_view(),name="producto_update"), 
    
    path("producto_create/",views.producto_create.as_view(),name="producto_create"),
    
    path("producto_delete/<int:pk>",views.producto_delete.as_view(),name="producto_delete"),
    
    path("producto_categoria_delete/<int:pk>",views.producto_categoria_delete.as_view(),name="producto_categoria_delete"),
    
    path("producto_categoria_update/<int:pk>",views.producto_categoria_update.as_view(),name="producto_categoria_update"), 

    path("error/",views.Error_view.as_view(),name="Error_view"),

]

PROYECTO/core/models.py
from django.db import models

# Create your models here.

PROYECTO/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User, Group, Permission




class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username","password"]
        widgets = {
            "username":forms.TextInput(attrs={"class":"form-control"}),

            "password":forms.PasswordInput(attrs={"class":"form-control"}),

        }

class Propio_UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(label="Nombre")
    last_name= forms.CharField(label = "Apellido")
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    
    class Meta:
      model = User
      fields = ['first_name','last_name','username', 'email', 'password1', 'password2']
      help_texts = {k:"" for k in fields}
    
    def save(self, commit=True):
        user = super().save(commit=commit)
        if commit:
            CLIENTES_NUEVOS_group = Group.objects.get(name="CLIENTES_NUEVOS")
            user.groups.add(CLIENTES_NUEVOS_group)
        return user

PROYECTO/core/views.py
from django.shortcuts import render
from .forms import CustomAuthenticationForm
from . import models
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from . import forms
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView
import os
from django.conf import settings


def home(request):
    return render(request,"core/index.html")

class CustomLoginView(LoginView):
    AuthenticationForm = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request: HttpRequest)-> HttpResponse:
    if request.method == "POST":
        form = forms.Propio_UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request,"core/index.html")
    else:
        form = forms.Propio_UserRegisterForm()
    return render(request,"core/register.html",context={"form":form})


class Error_view(TemplateView):
    template_name="producto/ERROR.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        error_image_path = os.path.join(settings.MEDIA_URL,'acceso_denegado.jpg')
        context[error_image_path]=error_image_path  
        return context

def about(request):
    return render(request,"core/about.html")

PROYECTO/core/templates/core/ERROR.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
{% endblock  %}

PROYECTO/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
    
<section class="page-section bg-primary" id="ABOUT">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/imagenes/about.webp'%}" alt="..." />
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Café fuerte, mente fuerte</span>
                            <P></P>
                            <span class="section-heading-lower">ACERCA DE NUESTRO  CAFÉ</span>
                        </h2>
                        <p>Nuestro establecimiento ha estado sirviendo un esquisito café procedente de agricultores artesanales provenientes de varias regiones del planeta. Nos dedicamos a viajar por el mundo, encontrar el mejor café y traerlo aquí en nuestra cafetería.</p>
                        <p class="mb-0">
                            Te garantizamos que caeras 
                            <em>encantado</em>
                            con nuestras deliciosas mezclas desde el momento en que entras hasta que terminas tu último sorbo.
                            Nos encantará formar parte de rutina, cuando sales con amigos o simplemente para disfrutar de un tiempo a solas.

                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<div class="product-item-description d-flex me-auto">
    <div class="bg-faded p-5 rounded"><p class="mb-0" style="font-size: 40px;">HOLA! SOY MATI, UN GUSTO!</p>
        <p class="mb-0" style="font-size: 15px;">
            Soy Matías Vargas, tengo 24 años y actualmente estoy estudiando Ingeniería Industrial en la UNLZ. 
            Estoy muy interesado por la programación, el ánalisis de datos y por supuesto que mi bebida favorita es el café.
            Esta es la primera Aplicación Web que realizo, estoy muy satisfecho con el resultaado a pesar de que aún hay muchas 
            cosas por mejorar, espero ir progresando con la práctica. Espero que te guste mi Aplicación Web y no olvides tomar tu Café
            o la bebida que más te guste. Nos vemos!!! 
            <div class="intro-button mx-auto"><a class="btn btn-primary btn-x3" href="https://www.linkedin.com/in/matias-vargas-07a841292/" target = "_blank">Linkedin</a></div>
        </p>
        </div><img class="img-fluid" src="{% static 'core/imagenes/perfil.png' %}" width="300" height="300"/>
    </div>
</div>


<a href="{% url 'core:Home' %}">

    <section class="page-section bg-primary" id="about">
      <div class="container px-4 px-lg-5">
          <div class="row gx-4 gx-lg-5 justify-content-center">
              <div class="col-lg-8 text-center">
                  <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
              </div>
          </div>
      </div>
  </section>
{% endblock contenido %}

PROYECTO/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="Café"/>
        <meta name="description" content="" />
        <meta name="author" content="Matías Vargas" />
        <title>La Esquina del Sabor</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">La Esquina del Sabor</span>
                <span class="site-heading-lower">Tu Dosis de Felicidad en Taza</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">ABOUT</a></li>
        
                        {% if user.is_authenticated %}
                        {% if user.username == 'admin' %} 
                            <li class="nav-item"><a class="nav-link" href="{% url 'cliente:Home' %}">CLIENTES</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'producto:Home' %}">PRODUCTOS</a></li>
                            <li class="nav-item"><a class="nav-link text-bg-warning">{{ user.username }}</a></li>
                            <li class="nav-item">
                            <form action="{% url 'core:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dark">SALIR</a></button>
                            </form>
                            </li>

                        {% else %}
                            
                            <li class="nav-item"><a class="nav-link" href="{% url 'producto:Home' %}">PRODUCTOS</a></li>
                            <li class="nav-item"><a class="nav-link text-bg-warning" >{{user.username}}</a></li>
                            <li class="nav-item">
                            <form action="{% url 'core:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dark">SALIR</a></button>
                            </form>
                            </li>
                        {% endif %}
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">INICIAR SESIÓN</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:register' %}">REGISTRARSE</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block titulo %}
        {% endblock titulo%}
        {% block contenido %}
        {% endblock contenido %}

        
</html>

PROYECTO/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
{% endblock titulo %}
{% block contenido %}

{% if user.is_authenticated %}

{{mensaje}}

{% endif %}    
<section class="page-section clearfix">
    <div class="container">
        <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/imagenes/intro.webp' %}" alt="..." />
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">Café que enamora</span>
                    <P></P>
                    <span class="section-heading-lower">Un momento para disfrutar</span>
                </h2>
                <p class="mb-3">Cada taza de nuestro café artesanal de calidad comienza con ingredientes finamente seleccionados. Una vez que lo pruebes, nuestro café será una maravillosa adición a tu rutina. </p>
                <span>¡Te lo garantizamos!</span>

                </p>
                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="https://wa.me/541133051014" target = "_blank">WhatsApp</a></div>
            </div>
        </div>
    </div>
</section>

<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Nuestra Promesa</span>
                        <P></P>
                        <span class="section-heading-lower">para vos</span>
                    </h2>
                    <p class="mb-0">Cuando ingresas a nuestro establecimiento para comenzar el día, estamos dedicados a brindarte un servicio amable, un ambiente cálido y, sobre todo, excelentes productos elaborados con ingredientes de la más alta calidad. Si no está satisfecho, háganoslo saber y haremos todo lo posible para arreglar las cosas.</p>
                </div>
            </div>
        </div>
    </div>
</section>
    


<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">VEN A VISITARNOS</span>
                        <span class="section-heading-lower">ESTAMOS ABIERTOS TODOS LOS DÍAS</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Domingo
                            <span class="ms-auto">9:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Lunes
                            <span class="ms-auto">7:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Martes
                            <span class="ms-auto">7:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Miércoles
                            <span class="ms-auto">7:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Jueves
                            <span class="ms-auto">7:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Viernes
                            <span class="ms-auto">7:00 a 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Sábado
                            <span class="ms-auto">9:00 a 00:00 </span>
                        </li>
                    </ul>
                    <p class="address mb-5" style="font-size: 2em;">
                        <em>
                            <strong>Avenida Las Heras 2450</strong>
                            <br />
                            Recoleta, CABA
                        </em>
                    </p>
                    <p class="mb-0" style="font-size: 2em;">
                        <em>Te esperamos!</em>
                   </p>
                </div>
            </div>
        </div>
    </div>
</section>



<footer class="footer text-faded text-center py-5">
    <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'core/js/scripts.js' %}></script>



{% endblock contenido %}

PROYECTO/core/templates/core/login.html
{% load static %}

{% block contenido %}
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="Café"/>
        <meta name="description" content="" />
        <meta name="author" content="Matías Vargas" />
        <title>La Esquina del Sabor</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>

    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">La Esquina del Sabor</span>
        <span class="site-heading-lower">Tu Dosis de Felicidad en Taza</span>
    </h1>


<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex me-auto rounded">
                    <h2 class="section-heading mb-0"> 
                        <span class="section-heading-lower">INICIAR SESIÓN</span>
                            <form method="post">
                                {% csrf_token %}
                                <table>
                                {{form.as_table}}
                                </table>
                                <button type="submit" class="btn btn-danger">INICIAR SESIÓN </button>
                                <a href="{% url 'core:Home' %}" class="btn btn-secondary">CANCELAR</a>     
                             </form>
                    </h2>
                </div>
            </div>
        </div>
    </div>
    
</section>


    
{% endblock contenido %}

PROYECTO/core/templates/core/logout.html
{% load static %}

{% block contenido %}
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="Café"/>
        <meta name="description" content="" />
        <meta name="author" content="Matías Vargas" />
        <title>La Esquina del Sabor</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>

    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">La Esquina del Sabor</span>
        <span class="site-heading-lower">Tu Dosis de Felicidad en Taza</span>
    </h1>
    
    <section class="page-section">
        <div class="container">
            <div class="product-item">
                <div class="product-item-title d-flex">
                    <div class="bg-faded p-5 d-flex me-auto rounded">
                        <h2 class="section-heading mb-0"> 
                            <span class="section-heading-lower">TEN UN BUEN DIA Y NO OLVIDES TOMAR TU CAFÉ!</span>
                        </h2>
                      </div>
                </div>
            </div>
          </div>
      </section> 

    <header>
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
            
            <span class="site-heading-lower">HAS</span>
            <P></P>
            <span class="site-heading-lower">CERRADO</span>
            <P></P>
            <span class="site-heading-lower"> SESIÓN</span>
            <P></P>
        </h1>
    </header>


          <a href="{% url 'core:Home' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                      </div>
                  </div>
              </div>
            </section></a>

{% endblock contenido %}

PROYECTO/core/templates/core/register.html
{% load static %}

{% block contenido %}
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="Café"/>
        <meta name="description" content="" />
        <meta name="author" content="Matías Vargas" />
        <title>La Esquina del Sabor</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>

    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">La Esquina del Sabor</span>
        <span class="site-heading-lower">Tu Dosis de Felicidad en Taza</span>
    </h1>


<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex me-auto rounded">
                    <h2 class="section-heading mb-0"> 
                        <span class="section-heading-lower">REGISTRO DE USUARIO</span>
                            <form method="post">
                                {% csrf_token %}
                                <table>
                                {{form.as_table}}
                                </table>
                                <button type="submit" class="btn btn-danger">REGISTRAR NUEVO USUARIO </button>
                                <a href="{% url 'core:Home' %}" class="btn btn-secondary">CANCELAR</a>     
                             </form>
                    </h2>
                </div>
            </div>
        </div>
    </div>
    
</section>


    
{% endblock contenido %}