PROYECTO/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from core import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("cliente/",include("cliente.urls")),
    path('productos/',include('producto.urls')),
    path('accounts/profile/', views.home, name='perfil'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PROYECTO/core/urls.py
from django.urls import path     
from django.contrib.auth.views import LogoutView     
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "core"



urlpatterns = [
    path("",views.home,name="Home"),
    path("login/",views.CustomLoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(template_name="core/logout.html"),name="logout"),
    path("register/",views.register,name="register"),
    path("error/",views.Error_view.as_view(),name="Error_view"),
    path("about/",views.about,name="about")
    
]


urlpatterns += staticfiles_urlpatterns()

PROYECTO/producto/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "producto"

urlpatterns = [
    path("",login_required(views.home),name="Home"),
    path("productocategoria/create/",views.productocategoria_create.as_view(),name="productocategoria_create"),

    path("productos_buscador_categoria/",login_required(views.home_1),name="buscador_productos"),
    
    path("productos_caracteristicas/<int:fk>",views.productos_caracteristicas,name="productos_caracteristicas"),
    
    path("producto_update/<int:pk>",views.producto_update.as_view(),name="producto_update"), 
    
    path("producto_create/",views.producto_create.as_view(),name="producto_create"),
    
    path("producto_delete/<int:pk>",views.producto_delete.as_view(),name="producto_delete"),
    
    path("producto_categoria_delete/<int:pk>",views.producto_categoria_delete.as_view(),name="producto_categoria_delete"),
    
    path("producto_categoria_update/<int:pk>",views.producto_categoria_update.as_view(),name="producto_categoria_update"), 

    path("error/",views.Error_view.as_view(),name="Error_view"),

]

PROYECTO/producto/models.py
from django.db import models

class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=200,unique=True)
    descripcion = models.CharField(max_length=250,null=True, blank=True,verbose_name='descripción')
    imagen = models.ImageField(upload_to="media",null=True)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "categoría de productos"

class Origen(models.Model):
    Origen_producto= models.CharField(max_length=200,unique=True)
    def __str__(self):

     return self.Origen_producto

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    categoria = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, null=True, verbose_name="categoría de productos")
    precio_producto = models.PositiveBigIntegerField(verbose_name="Precio")
    Origen_producto = models.ForeignKey(Origen, on_delete=models.SET_NULL, null=True, verbose_name="Origen del producto")
    imagen = models.ImageField(upload_to="media",null=True)
    
    def __str__(self):

     return self.nombre
     

PROYECTO/producto/forms.py
from django import forms
from . import models


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"
        widgets = {
            'imagen': forms.FileInput()
            }

class Producto_CreateForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        widgets = {
            'imagen': forms.FileInput()
            }

PROYECTO/producto/views.py
from django.shortcuts import render, redirect
from django import forms
from . import forms, models 
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView,TemplateView,UpdateView,DeleteView
import os
from django.conf import settings

def home(request):
    consulta_productos = models.ProductoCategoria.objects.all()
    context = {"productos":consulta_productos}
    return render(request,"producto/index.html",context)


def home_1(request):
    consulta = request.GET.get("consulta", None)
    
    if consulta:
        query = models.ProductoCategoria.objects.filter(nombre__icontains=consulta)
    else:
        query = models.ProductoCategoria.objects.all()

    context = {"productos":query}
    return render(request,"producto/buscador_productos.html",context)

    
class productocategoria_create(UserPassesTestMixin, LoginRequiredMixin, CreateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    template_name = "producto/productocategoria_create.html"
    success_url = reverse_lazy("producto:Home")

    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view") 
    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)
    
class Error_view(TemplateView):
    template_name="producto/ERROR.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        error_image_path = os.path.join(settings.MEDIA_URL,'acceso_denegado.jpg')
        context[error_image_path]=error_image_path  
        return context

class producto_create(UserPassesTestMixin, LoginRequiredMixin, CreateView):
    model = models.Producto
    form_class = forms.Producto_CreateForm
    template_name = "producto/producto_create.html"
    success_url = reverse_lazy("producto:buscador_productos")
    
    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view")
    
    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)
    

def productos_caracteristicas(request,fk):
    productos = models.Producto.objects.filter(categoria=fk)
    context = {"productos": productos}
    return render(request, "Producto/productos_caracteristicas.html", context)


class producto_update(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = models.Producto
    form_class = forms.Producto_CreateForm
    template_name = "producto/producto_update.html"
    success_url = reverse_lazy("producto:buscador_productos")

    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view")
    
   

class producto_delete(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model=models.Producto
    template_name = "producto/producto_delete.html"
    success_url = reverse_lazy("producto:buscador_productos")
    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view")


from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy


class producto_categoria_delete(UserPassesTestMixin, LoginRequiredMixin,DeleteView):
    model = models.ProductoCategoria
    template_name = "producto/producto_categoria_delete.html"
    success_url = reverse_lazy("producto:buscador_productos")
    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view")

class producto_categoria_update(UserPassesTestMixin, LoginRequiredMixin,UpdateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    template_name = "producto/producto_categoria_update.html"
    success_url = reverse_lazy("producto:buscador_productos")
    def test_func(self):
        return self.request.user.is_superuser 

    def handle_no_permission(self):
        return redirect("producto:Error_view")
    
    
    

    

PROYECTO/producto/templates/producto/ERROR.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
{% endblock  %}

PROYECTO/producto/templates/producto/buscador_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<head>
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
</head>

<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex me-auto rounded">
                    <h2 class="section-heading mb-0">
                        
                        <span class="section-heading-lower">CATEGORIAS DE PRODUCTOS</span>
                        
                    </h2>
                  </div>
            </div>
        </div>
      </div>
  </section>  

  <div class="col-md-3 pb-4">
    <div class="card-body align-self-md-center my-1">
      <form action="{% url 'producto:buscador_productos' %}" method="get">
        <input type="text" name="consulta" placeholder="Buscar..." style="background-color: rgb(221, 155, 68); color: rgb(255, 254, 253);
          width: 100%; /* Full width */
          padding: 10px; /* Padding */
          border: 10px solid burlywood; /* Border */
          border-radius: 50px; /* Rounded corners */
          font-size: 20px; /* Font size */
        ">
      </form>
    </div>
  </div>
</div>

<div class="row">
    {% for Producto in productos %}
        <div class="col-md-3 pb-4">
          <div class="card mb-3" style="background-color: burlywood; color: black;">  <div class="card-body align-self-md-center my-1 ">
              <h5 class="card-title text-nowrap" style="text-align: center;">{{ Producto.nombre }}<br>
                {% if Producto.imagen %}
                <img src="{{ Producto.imagen.url }}" width="400" height="200">
                {% endif %}
                <a href="{% url 'producto:productos_caracteristicas' Producto.id  %}"><br>
                 
                  <input class="bottons" type="submit" value="VER PRODUCTOS"> </a>
                   
                {% if user.is_authenticated %}
                {% if user.username == 'admin' %}
                  
                     
                  <a href="{% url 'producto:producto_categoria_delete' Producto.id  %}"><br>
                    <input class="bottons" type="submit" value="ELIMINAR CATEGORÍA"> </a> 
                  
                  <a href="{% url 'producto:producto_categoria_update' Producto.id  %}"><br>
                      <input class="bottons" type="submit" value="MODIFICAR CATEGORÍA"> </a> 
                  {% endif %}
                  {% endif %}
              </h5>
              <p><span class="fw-bold">Descripción: </span> {{ Producto.descripcion }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
  </div>
    



    <a href="{% url 'core:Home' %}">

      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
      </section>

    <footer class="footer text-faded text-center py-5">
      <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
  </footer>

  {% endblock contenido %}

PROYECTO/producto/templates/producto/index.html
    {% extends 'core/base.html' %}
    {% load static %}
    {% block  titulo%}
    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0"> 
                          <span class="section-heading-lower">PRODUCTOS HECHOS CON AMOR</span>
                      </h2>
                    </div>
              </div>
          </div>
        </div>
    </section>    
    {% endblock titulo %}

    {% block contenido %}

    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex ms-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">Mezclado a la perfección</span>
                          <p></p>
                          <span class="section-heading-lower">Café & Té</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-01_2.webp' %}" alt="..." />
              <div class="product-item-description d-flex me-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0">
                    Cada vez que nos pida una bebida, le garantizamos que será una experiencia que valdrá la pena vivir. 
                    Ya sea nuestro mundialmente famoso capuchino venezolano, un refrescante té de hierbas helado o algo tan simple como una taza de café negro especial,
                    le aseguramos que volverá por más.          </p>
                  </div>
              </div>
      </div>
  </section>
  <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">LA MEJOR COMIDA</span>
                          <p></p>
                          <span class="section-heading-lower">DESAYUNO, ALMUERZO, MERIENDA Y CENA</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-02.webp' %}" alt="..." />
              <div class="product-item-description d-flex ms-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0"></p>
                    Nuestro menú de temporada incluye productos horneados e incluso comidas completas perfectas para el desayuno, el almuerzo, la  merienda o la cena.
                    Obtenemos nuestros ingredientes de granjas orgánicas locales siempre que sea posible, junto con proveedores premium de productos especiales.</p></div>
              </div>
          </div>
      </div>
  </section>
  <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex ms-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">PROVENIENTES DE TODO EL MUNDO</span>
                          <p></p>
                          <span class="section-heading-lower">MAYORISTA EN MEZCLAS ESPECIALES</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-03.webp' %}" alt="..." />
              <div class="product-item-description d-flex me-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0">
                    Viajar por el mundo en busca del café de la mejor calidad es algo de lo que estamos orgullosos. 
                    Cuando nos visites, siempre encontrarás nuevas mezclas de todo el mundo, principalmente de regiones de Centro y Sudamérica. 
                    Vendemos nuestras mezclas en cantidades mayorista y minorista. Visítenos en persona para obtener más detalles
                  </p>
                  </div>
              </div>
          </div>
      </div>
  </section>
  
  <div class="fs-3 pb-4 ">
    <a href="{% url 'producto:buscador_productos' %}">
      <h1 class="site-heading text-center text-faded d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">CONSULTAR CATEGORIAS DE PRODUCTOS</span></a>
  </div> 
    
    </section>
    {% if user.is_authenticated %}
    {% if user.username == 'admin' %} 

    <div class="fs-3 pb-4 ">
      <a href="{% url 'producto:productocategoria_create' %}">
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">CREAR CATEGORÍAS DE PRODUCTO</span></a>
    </div> > 
    {% endif %}
    {% endif %}

    <a href="{% url 'core:Home' %}">

      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
    </section>

      </a>

      <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
    </footer>
    {% endblock  %}
    

PROYECTO/producto/templates/producto/producto_categoria_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ELIMINAR CATEGORIA DE PRODUCTOS</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4>ELIMINAR CATEGORÍA DE PRODUCTOS</h4>

            <span class="fs-5 fst-italic">¿Confirma que desea eliminar esta categoría?</span> 

            <form action="" method="post">
              {% csrf_token %}
              <input class="btn btn-danger" type="submit" value="CONFIRMAR">
            </form>
            
        </section>


        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/producto_categoria_update.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Formulario para modificar categoría</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4 class="text-center">FORMULARIO PARA MODIFICAR CATEGORÍA</h4>
            <form action="" method="post">
              {% csrf_token %}
              <table>
                {{form.as_table}}
              </table>
              <input class="bottons" type="submit" value="GUARDAR CAMBIOS"> </a>
            </form>
            
        </section>

        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A CATEGORIAS DE PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/producto_create.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Formulario de creación de productos</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4 class="text-center">FORMULARIO DE REGISTRO DE PRODUCTOS</h4>
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
          
              <table>
                {{form.as_table}}
              </table>
              
        
              <input class="botons" type="submit" value="REGISTRAR">
            </form>
            
        </section>


        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/producto_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ELIMINAR PRODUCTOS</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4>ELIMINAR PRODUCTOS</h4>

            <span class="fs-5 fst-italic">¿Confirma que desea eliminar este producto?</span> 

            <form action="" method="post">
              {% csrf_token %}
              <input class="btn btn-danger" type="submit" value="CONFIRMAR">
            </form>
            
        </section>


        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/producto_update.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Formulario para modificar productos</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4 class="text-center">FORMULARIO PARA MODIFICAR PRODUCTOS</h4>
            <form action="" method="post">
              {% csrf_token %}
              <table>
                {{form.as_table}}
              </table>
              <input class="bottons" type="submit" value="GUARDAR CAMBIOS"> </a>
            </form>
            
        </section>

        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A CATEGORIAS DE PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/productocategoria_create.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Formulario de creación de categoria de productos</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4 class="text-center">FORMULARIO DE REGISTRO DE CATEGORÍAS DE PRODUCTOS</h4>
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
          
              <table>
                {{form.as_table}}
              </table>
              
        
              <input class="botons" type="submit" value="REGISTRAR">
            </form>
            
        </section>

        <a href="{% url 'core:Home' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}

PROYECTO/producto/templates/producto/productos_caracteristicas.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Detalle de productos</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        
        <div class="row">
            {% for Producto in productos %}
              <div class="col-md-3 pb-4">  <div class="card mb-3" style="background-color: burlywood; color: black;">
                  <div class="card-body align-self-md-center my-1 ">
                    <h5 class="card-title text-nowrap">{{ Producto.nombre }}</h5>
                    <p class="card-text">
                      <span class="fw-bold">Precio: $</span> {{ Producto.precio_producto }} <br>
                      <span class="fw-bold">Origen: </span> {{ Producto.Origen_producto }} <br>
                    </p>
                  </div>
                  {% if Producto.imagen %}
                    <img src="{{ Producto.imagen.url }}" width="400" height="200">
                  {% endif %}
                  
                  {% if user.is_authenticated %}
                  {% if user.username == 'admin' %} 

                  <a href="{% url 'producto:producto_update' Producto.id %}"><br>
                    <input class="bottons" type="submit" value="MODIFICAR PRODUCTO">
                  </a>
                  <a href="{% url 'producto:producto_delete' Producto.id %}"><br>
                    <input class="bottons" type="submit" value="ELIMINAR PRODUCTO">
                  </a>
                  {% endif %}
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        
               
        </div>

        {% if user.is_authenticated %}
        {% if user.username == 'admin' %} 
        <div class="fs-3 pb-4 ">
            <a href="{% url 'producto:producto_create' %}">
              <h1 class="site-heading text-center text-faded d-none d-lg-block">
              <span class="site-heading-upper text-primary mb-3">AGREGAR PRODUCTO</span></a>
          </div> > 
          {% endif %}
          {% endif %}
            

        <a href="{% url 'core:Home' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}