PROYECTO/cliente/urls.py
from django.urls import path
from cliente import views
app_name = "cliente"

urlpatterns = [
    path("",views.home,name="Home"),
    path("cliente_create",views.cliente_create,name="cliente_create"),
    path("cliente_update/<int:pk>",views.cliente_update.as_view(),name="cliente_update"), 
    path("cliente_delete/<int:pk>",views.cliente_delete,name="cliente_delete"),
    path("cliente_detail/<int:pk>",views.cliente_detail,name="cliente_detail"), 
]

PROYECTO/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from core import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("cliente/",include("cliente.urls")),
    path('productos/',include('producto.urls')),
    path('accounts/profile/', views.home, name='perfil'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PROYECTO/core/urls.py
from django.urls import path     
from django.contrib.auth.views import LogoutView     
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "core"



urlpatterns = [
    path("",views.home,name="Home"),
    path("login/",views.CustomLoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(template_name="core/logout.html"),name="logout"),
    path("register/",views.register,name="register"),
    path("error/",views.Error_view.as_view(),name="Error_view"),
    path("about/",views.about,name="about")
    
]


urlpatterns += staticfiles_urlpatterns()

PROYECTO/producto/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "producto"

urlpatterns = [
    path("",login_required(views.home),name="Home"),
    path("productocategoria/create/",views.productocategoria_create.as_view(),name="productocategoria_create"),

    path("productos_buscador_categoria/",login_required(views.home_1),name="buscador_productos"),
    
    path("productos_caracteristicas/<int:fk>",views.productos_caracteristicas,name="productos_caracteristicas"),
    
    path("producto_update/<int:pk>",views.producto_update.as_view(),name="producto_update"), 
    
    path("producto_create/",views.producto_create.as_view(),name="producto_create"),
    
    path("producto_delete/<int:pk>",views.producto_delete.as_view(),name="producto_delete"),
    
    path("producto_categoria_delete/<int:pk>",views.producto_categoria_delete.as_view(),name="producto_categoria_delete"),
    
    path("producto_categoria_update/<int:pk>",views.producto_categoria_update.as_view(),name="producto_categoria_update"), 

    path("error/",views.Error_view.as_view(),name="Error_view"),

]

PROYECTO/cliente/models.py
from django.db import models

class suscripcion(models.Model):
    nivel = models.CharField(max_length=50)
    def __str__(self):

        return self.nivel

class Pais(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):

        return self.nombre
    
    class Meta:
        verbose_name_plural = 'Países'

class cliente(models.Model):
        nombre = models.CharField(max_length=200)

        apellido = models.CharField(max_length=50)

        nacimiento = models.DateField(null=True)

        pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, verbose_name="País de origen")

        nivel_sus = models.ForeignKey(suscripcion, on_delete=models.SET_NULL, null=True, verbose_name="Nivel")

        def __str__(self):
             return self.nombre

            

PROYECTO/cliente/forms.py
from django import forms
from . import models

class Clientes_form(forms.ModelForm):
    class Meta:
        model = models.cliente
        fields ="__all__"

PROYECTO/cliente/views.py
from django.shortcuts import render, redirect
from django import forms
from . import models, forms
from django.views.generic import UpdateView,TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

def home(request):
    consulta = request.GET.get("consulta", None)
    if consulta:
        query = models.cliente.objects.filter(nombre__icontains=consulta) 
    else:
        query = models.cliente.objects.all()
    context = {"clientes":query}
    return render(request,"cliente/index.html",context)


def cliente_create(request):
    if request.method == "POST":
        form = forms.Clientes_form(request.POST)
        if form. is_valid():
            form.save() 
            return redirect("cliente:Home")
    else:
        form = forms.Clientes_form()
    return render(request, "cliente/cliente_create.html",context={"form":form})


def cliente_detail(request,pk):
    cliente = models.cliente.objects.filter(id=pk)
    context = {"cliente": cliente}
    return render(request, "cliente/cliente_detail.html",context)



def cliente_delete(request,pk:int):
    query = models.cliente.objects.get(id=pk)
    if request.method == "POST":
            query.delete()
            return redirect("cliente:Home")
    return render(request,"cliente/cliente_delete.html",context = {"form":query})

class cliente_update(UpdateView):
    model = models.cliente
    form_class = forms.Clientes_form
    template_name = "cliente/cliente_update.html"
    success_url = reverse_lazy("cliente:Home")




    
 

PROYECTO/cliente/templates/cliente/cliente_create.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    {% if user.is_authenticated %}
    {% if user.username == 'admin' %} 

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
        <title>Formulario de creación de clientes</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
    </head>

    <body>
      <section class="form-register">
        <h4>FORMULARIO DE REGISTRO DE CLIENTES</h4>
        <form action="" method="post">
          {% csrf_token %}
      
          <table>
            {{form.as_table}}
          </table>

          <input class="botons" type="submit" value="REGISTRAR">
        </form>
      </section>
        
      <a href="{% url 'core:Home' %}">
     
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                  </div>
              </div>
          </div>
      </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>
        
        {% else %}
    <section class="page-section text-center">  <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex me-auto rounded">
            <h2 class="section-heading mb-0">
              <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </section>

  <a href="{% url 'core:Home' %}">

    <section class="page-section bg-primary" id="about">
      <div class="container px-4 px-lg-5">
          <div class="row gx-4 gx-lg-5 justify-content-center">
              <div class="col-lg-8 text-center">
                  <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
              </div>
          </div>
      </div>
  </section>
  {% endif %}
  
  {% else %}
  <section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
  {% endif %}
    
{% endblock contenido %}

PROYECTO/cliente/templates/cliente/cliente_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
{% if user.is_authenticated %}
{% if user.username == 'admin' %} 

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ELIMINAR PRODUCTOS</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4>ELIMINAR CLIENTE</h4>

            <span class="fs-5 fst-italic">¿Confirma que desea eliminar este cliente?</span> 

            <form action="" method="post">
              {% csrf_token %}
              <input class="btn btn-danger" type="submit" value="CONFIRMAR">
            </form>
            
        </section>


        <a href="{% url 'producto:buscador_productos' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A PRODUCTOS</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>
        
        {% else %}
        <section class="page-section text-center">  <div class="container">
          <div class="product-item">
            <div class="product-item-title d-flex">
              <div class="bg-faded p-5 d-flex me-auto rounded">
                <h2 class="section-heading mb-0">
                  <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
                </h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <a href="{% url 'core:Home' %}">
    
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                  </div>
              </div>
          </div>
      </section>
      {% endif %}
      {% else %}
  <section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
  
      {% endif %}
{% endblock contenido %}

PROYECTO/cliente/templates/cliente/cliente_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
{% if user.is_authenticated %}
{% if user.username == 'admin' %} 
  

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
        <title>Datos del clientes</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
    </head>

    <body>
        <section class="page-section">
            <div class="container">
            {% for Cliente in cliente %}
            <div class="product-item">
                <div class="product-item-title d-flex">
                    <div class="bg-faded p-5 d-flex me-auto rounded">
                        <h2 class="section-heading mb-0"> 
                            <span class="section-heading-lower">{{ Cliente.nombre }} {{Cliente.apellido}} </span>
                            <p></p>
                            <span class="fw-bold">Nacionalidad: </span> {{Cliente.pais_origen_id }}<br>
                            <p></p>
                            <span class="fw-bold">Nacimiento: </span> {{ Cliente.nacimiento|date:"d/m/Y" }} <br>
                            <p></p>
                            <span class="fw-bold">País de origen: </span> {{ Cliente.pais_origen_id }}<br>
                            <p></p>
                            <span class="fw-bold">Nivel: </span> {{ Cliente.nivel_sus }}
                        </h2>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>

    <SECtion>
      <a href="{% url 'cliente:Home' %}">
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER A CLIENTES</h2>
                  </div>
              </div>
          </div>
      </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>
        
        {% else %}
        <section class="page-section text-center">  <div class="container">
          <div class="product-item">
            <div class="product-item-title d-flex">
              <div class="bg-faded p-5 d-flex me-auto rounded">
                <h2 class="section-heading mb-0">
                  <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
                </h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <a href="{% url 'core:Home' %}">
    
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                  </div>
              </div>
          </div>
      </section>
      {% endif %}
      {% else %}
  <section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
 
      {% endif %}
    
{% endblock contenido %}

PROYECTO/cliente/templates/cliente/cliente_update.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
{% if user.is_authenticated %}
{% if user.username == 'admin' %} 
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Formulario para modificar clientes</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>
        <section class="form-register">
            <h4>FORMULARIO PARA MODIFICAR DATOS DE CLIENTES</h4>
            <form action="" method="post">
              {% csrf_token %}
              <table>
                {{form.as_table}}
              </table>
              <input class="bottons" type="submit" value="GUARDAR CAMBIOS"> </a>
            </form>
            
        </section>

        <a href="{% url 'cliente:Home' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER A CLIENTES</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>
        {% else %}
        <section class="page-section text-center">  <div class="container">
          <div class="product-item">
            <div class="product-item-title d-flex">
              <div class="bg-faded p-5 d-flex me-auto rounded">
                <h2 class="section-heading mb-0">
                  <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
                </h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <a href="{% url 'core:Home' %}">
    
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                  </div>
              </div>
          </div>
      </section>
      {% endif %}
      {% else %}
  <section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>

      {% endif %}
{% endblock contenido %}

PROYECTO/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}
{% load static %}
    {% block  titulo%}

    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0">
                          
                          <span class="section-heading-lower">CLIENTES</span>
                          
                      </h2>
                    </div>
              </div>
          </div>
        </div>
    </section> 
    {% endblock titulo %}

    {% block contenido %}
    {% if user.is_authenticated %}
    {% if user.username == 'admin' %} 
      
    
    <div class="col-md-3 pb-4">
        <div class="card-body align-self-md-center my-1">
          <form action="{% url 'cliente:Home' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar..." style="background-color: rgb(221, 155, 68); color: rgb(255, 254, 253);
              width: 100%; /* Full width */
              padding: 10px; /* Padding */
              border: 10px solid burlywood; /* Border */
              border-radius: 50px; /* Rounded corners */
              font-size: 20px; /* Font size */
            ">
          </form>
        </div>
      </div>
    </div>

        
    <div class="row">
      {% for Cliente in clientes %}
      <div class="col-md-3 pb-4">
        <div class="card mb-3" style="background-color: burlywood; color: black;">  <div class="card-body align-self-md-center my-1 ">
            <h5 class="card-title text-nowrap">{{ Cliente.nombre }} {{Cliente.apellido}}</h5>
            <p class="card-text">
              <a href="{% url 'cliente:cliente_detail' Cliente.id  %}"><br>
                <input class="btn btn-dark" type="submit" value="       VER DATOS       "> </a>
              <a href="{% url 'cliente:cliente_delete' Cliente.id  %}"><br>
              <input class="btn btn-danger " type="submit" value="ELIMINAR CLIENTE"> </a>
              <a href="{% url 'cliente:cliente_update' Cliente.id  %}"><br>
                <input class="bottons" type="submit" value="MODIFICAR CLIENTE"> </a> </p>
            </h5>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
      
    <div class="fs-3 pb-4 ">
      <a href="{% url 'cliente:cliente_create' %}">
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">CREAR CLIENTES</span></a>
    </div> 

    <a href="{% url 'core:Home' %}">
     
      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
    </section>


    </a>
        
      <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
    </footer>

    {% else %}
    <section class="page-section text-center">  <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex me-auto rounded">
            <h2 class="section-heading mb-0">
              <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </section>

  <a href="{% url 'core:Home' %}">

    <section class="page-section bg-primary" id="about">
      <div class="container px-4 px-lg-5">
          <div class="row gx-4 gx-lg-5 justify-content-center">
              <div class="col-lg-8 text-center">
                  <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
              </div>
          </div>
      </div>
  </section>
  {% endif %}
  {% else %}
  <section class="page-section text-center">  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex me-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-lower">NO TIENES ACCESO PARA ENTRAR EN ESTA SECCIÓN!!! CONTACTA AL ADMINISTRADOR!!!</span>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<a href="{% url 'core:Home' %}">

  <section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
            </div>
        </div>
    </div>
</section>
  {% endif %}


    {% endblock contenido%}